package com.rex.crm.db.model;

// Generated 2013-5-4 16:44:24 by Hibernate Tools 4.0.0

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private Integer cityId;
	private String classification;
	private Boolean isKeyAccount;
	private String level;
	private String photo;
	private String status;
	private String tele;

	public Account() {
	}

	public Account(String name) {
		this.name = name;
	}

	public Account(String name, String address, Integer cityId,
			String classification, Boolean isKeyAccount, String level,
			String photo, String status, String tele) {
		this.name = name;
		this.address = address;
		this.cityId = cityId;
		this.classification = classification;
		this.isKeyAccount = isKeyAccount;
		this.level = level;
		this.photo = photo;
		this.status = status;
		this.tele = tele;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public Boolean getIsKeyAccount() {
		return this.isKeyAccount;
	}

	public void setIsKeyAccount(Boolean isKeyAccount) {
		this.isKeyAccount = isKeyAccount;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTele() {
		return this.tele;
	}

	public void setTele(String tele) {
		this.tele = tele;
	}

}
