package com.rex.crm.db.model;

// Generated 2013-5-4 16:44:24 by Hibernate Tools 4.0.0

/**
 * Accountcrmuser generated by hbm2java
 */
public class Accountcrmuser implements java.io.Serializable {

	private Integer id;
	private int accountId;
	private int crmuserId;

	public Accountcrmuser() {
	}

	public Accountcrmuser(int accountId, int crmuserId) {
		this.accountId = accountId;
		this.crmuserId = crmuserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public int getCrmuserId() {
		return this.crmuserId;
	}

	public void setCrmuserId(int crmuserId) {
		this.crmuserId = crmuserId;
	}

}
