package com.rex.crm.db.model;

// Generated 2013-5-4 16:44:24 by Hibernate Tools 4.0.0

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private Integer id;
	private int crmuserId;
	private Long endtime;
	private long starttime;
	private String title;
    private int event_type;
    private int status;
	public Activity() {
	}

	public Activity(int crmuserId, long starttime) {
		this.crmuserId = crmuserId;
		this.starttime = starttime;
	}

	public Activity(int crmuserId, Long endtime, long starttime, String title) {
		this.crmuserId = crmuserId;
		this.endtime = endtime;
		this.starttime = starttime;
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCrmuserId() {
		return this.crmuserId;
	}

	public void setCrmuserId(int crmuserId) {
		this.crmuserId = crmuserId;
	}

	public Long getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Long endtime) {
		this.endtime = endtime;
	}

	public long getStarttime() {
		return this.starttime;
	}

	public void setStarttime(long starttime) {
		this.starttime = starttime;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getEvent_type() {
		return event_type;
	}

	public void setEvent_type(int event_type) {
		this.event_type = event_type;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	
}
