package com.rex.crm.db.model;

// Generated 2013-5-4 16:44:24 by Hibernate Tools 4.0.0

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer id;
	private String name;
	private String provinceId;

	public City() {
	}

	public City(String name, String provinceId) {
		this.name = name;
		this.provinceId = provinceId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

}
