package com.rex.crm.db.model;

// Generated 2013-5-4 16:44:24 by Hibernate Tools 4.0.0

/**
 * Crmuser generated by hbm2java
 */
public class Crmuser implements java.io.Serializable {

	private Integer id;
	private String name;
	private String department;
	private String division;
	private String cellPhone;
	private String email;
	private String employeeNumber;
	private String photo;
	private String jobTitle;
	private int cityId;

	public Crmuser() {
	}

	public Crmuser(String name, int cityId) {
		this.name = name;
		this.cityId = cityId;
	}

	public Crmuser(String name, String department, String division,
			String cellPhone, String email, String employeeNumber,
			String photo, String jobTitle, int cityId) {
		this.name = name;
		this.department = department;
		this.division = division;
		this.cellPhone = cellPhone;
		this.email = email;
		this.employeeNumber = employeeNumber;
		this.photo = photo;
		this.jobTitle = jobTitle;
		this.cityId = cityId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

}
