package com.rex.crm.db.model;

// Generated 2013-5-4 16:44:24 by Hibernate Tools 4.0.0

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private Integer id;
	private String name;

	public Province() {
	}

	public Province(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
